### ISSUE TITLE
As a Web component Store manager I want to have the Events Web Component online

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events#1]

**Comment by Piiit** [comment]
@sseppi There is no PR at the moment...

**Comment by sseppi** [comment]
The link to the component on our testing environment:

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/1cba7d30-8331-4b4a-b528-c4e03279365c

**Comment by lcfd** [comment]
@sseppi

This issue should be solved

cc @GnuRant
