### ISSUE TITLE
Some configurations are missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events#11]
According to the Briefing sent some configurations of the web component on the web component store are missing.

In particular actually for a web component store user are missing the following configuration opportunity:
- [x] set a radius for the query of the events;
- [x] select the types of events (e.g. sport, fair, theatre, music, etc.) to be shown;
- [x] activate/deactivate the “get directions” button. The button could redirect the user to google maps for the navigation.
- [x] Integrate the activate direction attribute in the manifest.json file @dulvui 

@GnuRant

**Comment by lcfd** [comment]
Hi, @sseppi @Piiit point 1 and 3 are in PR.
Point 2 is still on hold due to filter level decisions.

cc @GnuRant

**Comment by Piiit** [comment]
@lcfd @GnuRant
We decided to always take the categories from the API, and always do the call and not hardcode them inside JS. Event types should be configurable, that means give a list which should be shown (whitelisting). Or show all if not list has been given.

**Comment by lcfd** [comment]
@Piiit
Ok, which endpoint do I have to use?

**Comment by RudiThoeni** [comment]
http://tourism.opendatahub.bz.it/api/EventTopics

**Comment by Piiit** [comment]
@dulvui Please fix the wcs-manifest.json

@lcfd Done for Belka, thanks...

**Comment by sseppi** [comment]
After testing all configurations described in this issue seems to work fine.
