### ISSUE TITLE
Some detail views do not have a scrollbar when needed, and thus hide content

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-events#27]
**PLEASE VERIFY AND PR ON ALL ONGOING WEB COMPONENTS**

- [x] meteo-generic
- [x] events
- [x] parking
- [x] gastronomies
- [x] mountain-area

**Comment by GnuRant** [comment]
è su tutti i WC

**Comment by lcfd** [comment]
Really strange because when used on an HTML page it's correctly working.
Can you check on your store if the component has the dimensions set?
(We have tested responsiveness many times.)

```
<webcomp-events
  width="100%"
  height="500px"
  fontFamily="Arial"
  language="it"
  mapAttribution='&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  currentLocation='{ "lat": 46.5, "lng": 11.3 }'
  tiles-url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  modality="map"
  pageSize="5"
  -filterRadius="5"
  disableEventDirections
  categoriesFilter="[8,16]"
></webcomp-events>
```

<img width="1219" alt="Screenshot 2021-03-31 at 16 52 55" src="https://user-images.githubusercontent.com/9001053/113164883-cf193f80-9241-11eb-866a-1fafce65c92c.png">

**Comment by Piiit** [comment]
Try with a height in percentages... and a container with a fixed height.

```html
<div style="height: 800px">
<webcomp-events
  width="100%"
  height="100%"
  fontFamily="Arial"
  language="it"
  mapAttribution='&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  currentLocation='{ "lat": 46.5, "lng": 11.3 }'
  tiles-url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  modality="map"
  pageSize="5"
  -filterRadius="5"
  disableEventDirections
  categoriesFilter="[8,16]"
></webcomp-events>
</div>
```

**Comment by lcfd** [comment]
@Piiit  Fixed on webcomp-events, I'll proceed with doing a check on what other components need the fix
