### ISSUE TITLE
The web componet doesnt use the coordinates input as configuration.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events#4]
If I change the GPS coordinate of the`map centre (```currentLocation="{ 'lat': 46.31, 'lng': 11.26 }"```) of the map the web component doesn't change map centre even if in the code snippet the coordinates are properly seen.

It seems that the ```currentLocation``` parameter isn't properly managed by the web component store since, if I try the external view in the URL it seems to be ecoded wrong ```currentLocation="{ 'lat'%3A 46.31%2C 'lng'%3A 11.26 }"```.

@GnuRant

**Comment by lcfd** [comment]
@sseppi

As said in call this is a problem with the web component store way of use HTML parameters.
This issue is linked to the decision of maintain this semantic lit-element w.c. way or split the parameter in two.

cc @GnuRant

**Comment by Piiit** [comment]
Hi, we decided to split them for an easier use and due to the fact, that we cannot fix the store at the moment. So for an integration this splitting is needed. Thank you for your understanding...

**Comment by lcfd** [comment]
@Piiit @sseppi The issue is about a problem with the wc store and the management of the parameters.
So for the refactor of the parameters we will need a new issue.
