### ISSUE TITLE
Null in the contact info

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-events#8]
Once a specific info In the contact info 2 null are always shown after the address.
![Schermata da 2021-01-13 19-06-58](https://user-images.githubusercontent.com/7909989/104491629-d0d44f00-55d2-11eb-9815-c49508583fd9.png)
@GnuRant @lcfd

**Comment by Piiit** [comment]
@lcfd Is this issue to review? Please move it to the column inside the kanban if so...

Thanks :-)

**Comment by dulvui** [comment]
I deployed PR with Issue 8 on test WebStore with version 1.0.2
